version: '3.1'
services:


  web:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    network_mode: bridge
    depends_on:
      - db
    links:
      - db

  db:
    image: localstack/localstack
    container_name: aws
    network_mode: bridge
    ports:
      - "4567-4583:4567-4583"
      - "4560:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - SERVICES=dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock