---
swagger: '2.0'
info:
  title: Robot navigation API
  version: 0.0.1
basePath: /dev
consumes:
  - application/json
produces:
  - application/json
paths:
  /ping:
    get:
      summary: Test API point
      description: Returns 'pong' at success
      produces:
        - html/text
      responses:
        200: Pong
  /location:
    post:
      description: |
        Save path to db
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/location'
  /location/batch_save:
    post:
      description: |
        Save path to db
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/locations'

      responses:
        200: Success
  /location/{location_name}:
    get:
      parameters:
        - name: location_name
          in: path
      responses:
        200: Success
  /dynamo:
    get:
      description: Get table content

definitions:
  location:
    id: Location
    type: object
    required: [name, x, y]
    properties:
      name:
        type: string
      x:
        type: number
        minimum: 0
      y:
        type: number
        minimum: 0
  locations:
    id: Locations
    type: array
    minItems: 1
    items:
      schema:
        $ref: '#/definitions/location'








